version: '3'

includes:
  # Documentation tasks
  docs:
    taskfile: ./docs/Taskfile.yaml
    dir: ./docs

tasks:
  generate:
    desc: Run code generation (deepcopy, defaults)
    deps:
      - task: docs:generate