# This rule is not used by the project fraud itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the fraud.miloapis.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fraud
    app.kubernetes.io/managed-by: kustomize
  name: fraudpolicy-editor-role
rules:
- apiGroups:
  - fraud.miloapis.com
  resources:
  - fraudpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fraud.miloapis.com
  resources:
  - fraudpolicies/status
  verbs:
  - get
