resources:
- role.yaml
- role_binding.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
# For each CRD, "Admin", "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the fraud itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- fraudevaluation_admin_role.yaml
- fraudevaluation_editor_role.yaml
- fraudevaluation_viewer_role.yaml
- fraudpolicy_admin_role.yaml
- fraudpolicy_editor_role.yaml
- fraudpolicy_viewer_role.yaml
- fraudprovider_admin_role.yaml
- fraudprovider_editor_role.yaml
- fraudprovider_viewer_role.yaml
