apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fraud-system
namePrefix: fraud-

resources:
  - ../rbac
  - ../manager
  - ../default/metrics_service.yaml

components:
  - ../prometheus
  - ../resourcemetrics

patches:
  - path: ../default/manager_metrics_patch.yaml
    target:
      kind: Deployment
