apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fraud-system
namePrefix: fraud-

resources:
  - ../manager
  - metrics_service.yaml

components:
  - ../prometheus

patches:
  - path: manager_metrics_patch.yaml
    target:
      kind: Deployment
